### ISSUE TITLE
CC-BY-SA-4.0 not suitable for this repository

### ISSUE THREAD

**Issue by drizmiz** [Honour-Van/CS50#1]
The CC-BY-SA-4.0 License is supposedly not suitable for this repository, which contains source code.

[https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering [licenses listed as free](https://www.gnu.org/licenses/license-list#SoftwareLicenses) by the [Free Software Foundation](https://www.fsf.org/) and [listed as “open source”](https://opensource.org/licenses) by the [Open Source Initiative](http://www.opensource.org/).

**Comment by Honour-Van** [comment]
Thanks a lot
