### ISSUE TITLE
地铁刷卡数据

### ISSUE THREAD

**Issue by YogeLiu** [Honour-Van/CS50#2]
学长，你好，请问你手上就只有这100000万条数据吗？我看着好像不够24小时的

**Comment by Honour-Van** [comment]
是有完整版的，git lfs限额不够了，就没有传，可以私聊联系我。另外我可能不是学长，我才大三……

**Comment by YogeLiu** [comment]
怎么加你呢

**Comment by Honour-Van** [comment]
不好意思，因为是邮件发过来的，以为我的邮箱是公布的，我现在把邮件放到profile了，fhn037 at 126.com

**Comment by YogeLiu** [comment]
我有发邮箱过去，你有收到吗。同学
